<?php

/**
 * @file
 * Module implementing a field-collection table formatter.
 */

/**
 * Implements hook_menu().
 */
function field_collection_table_menu() {
  $items = array();

  $items['admin/config/user-interface/field_collection_table'] = array(
    'title' => 'Field Collection Table settings',
    'description' => 'Configuration of Field Collection Table module options.',
    'file' => 'field_collection_table.admin.inc',
    'file path' => drupal_get_path('module', 'field_collection_table') . '/includes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('field_collection_table_admin_settings'),
    'access arguments' => array('administer field-collections'),
  );

  return $items;
}

/**
 * Implements hook_field_formatter_info().
 */
function field_collection_table_field_formatter_info() {
  return array(
    'field_collection_table_view' => array(
      'label' => t('Table field-collection items'),
      'field types' => array('field_collection'),
      'settings' =>  array(
        'edit' => t('Edit'),
        'delete' => t('Delete'),
        'add' => t('Add'),
        'description' => TRUE,
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function field_collection_table_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];

  switch ($display['type']) {
    case 'field_collection_table_view':
      $header = array();
      $field_names = array();
      foreach (field_info_instances('field_collection_item', $field['field_name']) as $field_collection_item) {
        $weight = $field_collection_item['display']['default']['weight'];
        $field_names[$weight] = $field_collection_item['field_name'];
        $header[$weight] = array(
          'data' => $field_collection_item['label'],
          'class' => $field_names[$weight],
        );
      }
      ksort($header);
      ksort($field_names);

      $rows = array();
      foreach ($items as $delta => $item) {
        $field_collection = field_collection_field_get_entity($item);
        if (empty($field_collection)) {
          continue;
        }
        $view = $field_collection->view();
        $content = $view['field_collection_item'][$field_collection->identifier()];
        $column = array();
        foreach ($field_names as $field_name) {
          if (isset($content[$field_name])) {
            $content[$field_name]['#label_display'] = 'hidden';
          }
          else {
            $content[$field_name] = array(
              '#markup' => '<span class="empty_field"></span>',
              '#empty' => TRUE,
            );
          }
          $column[] = array(
            'data' => $content[$field_name],
            'class' => $field_name,
          );
        }

        $links = array(
          '#theme' => 'links',
          '#theme_wrapper' => 'item_list',
          '#attributes' => array(
            'class' => array(
              'field-collection-view-links',
            ),
          ),
        );

        foreach (array('edit', 'delete') as $op) {
          if (!empty($settings[$op]) && field_collection_item_access($op == 'edit' ? 'update' : $op, $field_collection)) {
            $links['#links'][$op] = array(
              'title' => $settings[$op],
              'href' => $field_collection->path() . '/' . $op,
              'query' => drupal_get_destination(),
            );
            $header['operations'] = t('Operations');
          }
        }

        if (!empty($links['#links'])) {
          $column[] = array(
            'data' => $links,
            'class' => "field_collection_item_operations",
          );
        }

        $rows[] = array(
          'data' => $column,
          'class' => array('field_collection_item'),
        );
      }

      $element[0] = array(
        '#theme' => 'table',
        '#header' => $header,
        '#rows' => $rows,
      );

      if (variable_get('field_collection_table_hide_empty', FALSE)) {
        $element[0]['#theme'] = 'table__field_collection_table';
        $element[0]['#settings']['empty'] = TRUE;
      }
      break;
  }

  field_collection_field_formatter_links($element, $entity_type, $entity, $field, $instance, $langcode, $items, $display);

  return $element;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function field_collection_table_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  return field_collection_field_formatter_settings_form($field, $instance, $view_mode, $form, $form_state);
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function field_collection_table_field_formatter_settings_summary($field, $instance, $view_mode) {
  return field_collection_field_formatter_settings_summary($field, $instance, $view_mode);
}

/**
 * Implements hook_theme().
 */
function field_collection_table_theme($existing, $type, $theme, $path) {
  $base = array(
    'file' => 'theme.inc',
    'path' => $path . '/theme',
  );
  return array(
    'field_collection_table_multiple_value_field' => $base + array(
      'render element' => 'element',
    ),
    'field_collection_table_multiple_value_fields' => $base + array(
      'render element' => 'element',
    ),
    'table__field_collection_table' => $base + array(
      'variables' => array(
        'header' => NULL,
        'rows' => NULL,
        'attributes' => array(),
        'caption' => NULL,
        'colgroups' => array(),
        'sticky' => TRUE,
        'empty' => '',
        'settings' => array(),
      ),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function field_collection_table_form_alter(&$form, &$form_state, $form_id) {
  if (!variable_get('field_collection_table_format_form', TRUE)) {
    return;
  }

  if (isset($form['#entity_type']) && isset($form['#bundle'])) {
    foreach (field_info_instances($form['#entity_type'], $form['#bundle']) as $field_name => $instance) {
      $field_info = field_info_field($field_name);
      if ($field_info['type'] == 'field_collection') {
        if (isset($form[$field_name])) {
          $language = $form[$field_name]['#language'];
          $form[$field_name][$language]['#theme'] = 'field_collection_table_multiple_value_fields';
          $form[$field_name][$language]['#pre_render'][] = 'field_collection_table_pre_render_multiple_fields';
        }
      }
    }
  }
  if ($form_id == 'field_collection_item_form') {
    $form['#theme'] = 'field_collection_table_multiple_value_field';
    $form['#pre_render'][] = 'field_collection_table_pre_render_field';
  }
}

/**
 * Callback for #pre_render for a single row, hide the titles for each field.
 */
function field_collection_table_pre_render_field($element) {
  foreach (field_info_instances($element['#entity_type'], $element['#bundle']) as $field_name => $instance) {
    if (empty($element[$field_name])) {
      continue;
    }

    $field = &$element[$field_name];
    $language = $field['#language'];
    if (isset($field[$language])) {
      // Set the most common places for a title to display invisible.
      $field['#title_display'] = 'invisible';
      $field[$language]['#title_display'] = 'invisible';
      foreach (element_children($field[$language]) as $child) {
        $field[$language][$child]['#title_display'] = 'invisible';
        $field[$language][$child]['value']['#title_display'] = 'invisible';
      }
    }
    else {
      $field['#label_display'] = 'hidden';
    }
  }
  return $element;
}

/**
 * Callback for #pre_render for multiple rows, hide the titles for each field.
 */
function field_collection_table_pre_render_multiple_fields($element) {
  foreach (element_children($element) as $key) {
    // Skip the 'add_more' element.
    if (is_numeric($key)) {
      $element[$key] = field_collection_table_pre_render_field($element[$key]);
    }
  }
  return $element;
}

/**
 * Implements hook_entity_view().
 */
function field_collection_table_entity_view($entity, $type, $view_mode, $langcode) {
  if (get_class($entity) != 'FieldCollectionItemEntity') {
    return;
  }

  $display = field_get_display($entity->instanceInfo(), $view_mode, $entity->hostEntity());
  if ($display['type'] == 'field_collection_table_view') {
    $entity->content['#theme'] = 'field_collection_table_multiple_value_field';
    $entity->content['#pre_render'][] = 'field_collection_table_pre_render_field';
  }
}
